version: '3.9'
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - PUBLIC_IP=3.35.13.158
      - PUBLIC_PORT=8211
      - SERVER_NAME=charon-docker-generated-123
      - SERVER_DESCRIPTION=Palworld-Dedicated-Server running in Docker by charon
      - SERVER_PASSWORD=etech1234
      - ADMIN_PASSWORD=etech1234
    volumes:
      - ./game:/palworld
  
  rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', '3.35.13.158:25575', '-p', 'etech1234']
    profiles: ['rcon'] 
